# Generated by Django 5.2.14 on 2026-05-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the domain', null=True, upload_to='domains/'),
        ),
    ]
