# Generated by Django 6.0.5 on 2026-05-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For hierarchical categorization (e.g., Kitchen > Appliances)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomains', to='core.domain'),
        ),
    ]
