# Generated by Django 5.2.14 on 2026-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domain_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
