# Generated by Django 5.2.14 on 2026-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_ai_generated_item_generation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
