# Generated by Django 5.2.14 on 2026-06-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_domain_ai_generated_domain_generation_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
